### ISSUE TITLE
How to pass cdk deploy arguments?

### ISSUE THREAD

**Issue by fsmikedev** [codebrewlab/nx-plugins#1]
Hi, 

I'm trying to set a parameter value when deploying but I can't get it to work.

Thanks.

**Comment by tienne** [comment]
May I know the command that you tried?

**Comment by fsmikedev** [comment]
Sure, I'm trying to pass a context key value e.g.
`nx deploy cdk-test --context key=value`

**Comment by tienne** [comment]
I have deployed the v1.0.0 version to enable option use. Please get the package updated and check it out.

**Comment by fsmikedev** [comment]
Thank you for adding that, it's working now.

**Comment by tienne** [comment]
Do you have any other questions or help?

**Comment by fsmikedev** [comment]
Not at the moment, thanks.

**Comment by tienne** [comment]
All right. close the issue.
