### ISSUE TITLE
Destroy doesn't work

### ISSUE THREAD

**Issue by w0otness** [codebrewlab/nx-plugins#3]
First issue:
In Line 10: /packages/nx-aws-cdk/executors.json
`"implementation": "./src/executors/destroy/executor",`
needs to be 
`"implementation": "./src/executors/destroy/destroy",`

Second:
Once the first fix is made in my node_modules, the command works without error, though it doesn't remove the stack, and `Executing command: cdk destroy` is output to command line.

Side Note:
I'm using aws-cdk 2.9.0, aws-cdk-lib 2.9.0 and constructs 10.0.46, and the stack deployed just fine.

It might also help to document the process for providing the credentials via environment variables. 

I personally used `npm install -D env-cmd` and made a `.env.json` in the base folder with `{
  "AWS_ACCESS_KEY_ID": "",
  "AWS_SECRET_ACCESS_KEY": ""
}`, and added .env.json to .gitignore.
 
Then called `npm exec env-cmd nx r cdk:deploy`.

**Comment by tienne** [comment]
Thank you for registering the issue.

The issue has been modified in version 1.0.2.
Please enjoy it.

**Comment by w0otness** [comment]
Version 1.0.2 does fix the first part of this issue.

However `npm exec env-cmd nx r cdk:destroy` still outputs `Executing command: cdk destroy` without removing the cloudformation stack.

Going to test whether this is due to using 2.9.0 of CDK.

**Comment by w0otness** [comment]
Got it!
Line 18: packages/nx-aws-cdk/src/executors/destroy/destroy.ts
`  const result = runDestroy(normalizedOptions, context);`
to
`  const result = await runDestroy(normalizedOptions, context);`

and 
Line 25: packages/nx-aws-cdk/src/executors/destroy/destroy.ts
`function runDestroy(options: ParsedDestroyExecutorOption, context: ExecutorContext) {`
to
`async function runDestroy(options: ParsedDestroyExecutorOption, context: ExecutorContext) {`

Just replicated what deploy was doing!

**Comment by w0otness** [comment]
New problem!
Now it asks:
`Are you sure you want to delete: <stackname> (y/n)?`
and you can't enter y or n, and have to ctrl-c to exit.

**Comment by w0otness** [comment]
change Line 26: packages/nx-aws-cdk/src/executors/destroy/destroy.ts
`  const command = createCommand('destroy', options);`
to
`  const command = createCommand('destroy -f', options);`

That successfully deletes the stack for me.
